#!/bin/bash

import math

def factorize(n):
	for i in range(2, int(math.sqrt(n)) + 1):
		if n % i == 0:
		return '{}={}*{}'.format(n, i, n // i)
		return '{} is prime'.format(n)

		with open('file.txt', 'r') as f:
		for line in f:
	n = int(line.strip())
print(factorize(n))
