#!/bin/bash

import math
import sys

def factorize(n):
for i in range(2, int(math.sqrt(n)) + 1):
	if n % i == 0:
		return '{}={}*{}'.format(n, i, n // i)
		return '{}=1*{}'.format(n, n)

		def main(filename):
		with open(filename, 'r') as f:
		for line in f:
			n = int(line.strip())
			print(factorize(n))

			if __name__ == '__main__':
				if len(sys.argv) != 2:
					print('Usage: factors <file>')
				else:
					main(sys.argv[1])






					python factors.py input.txt
