#!/bin/bash

import math
import sys
from random import randint

def gcd(a, b):
while b:
	a, b = b, a % b
	return a

	def pollard_rho(n):
	x = y = 2
	d = 1
	while d == 1:
		x = (x*x + 1) % n
		y = (y*y + 1) % n
		y = (y*y + 1) % n
		d = gcd(abs(x - y), n)
		if d == n:
			return None
		else:
			return d

			def factorize(n):
			p = pollard_rho(n)
			q = n // p
			return '{}={}*{}'.format(n, p, q)

			def main(filename):
			with open(filename, 'r') as f:
			n = int(f.readline().strip())
			print(factorize(n))

			if __name__ == '__main__':
				if len(sys.argv) != 2:
					print('Usage: rsa_factors <file>')
				else:
					main(sys.argv[1])
