#!/bin/bash

import sys

def factorize(n):
for i in range(2, n):
	if n % i == 0:
		return "{}={}*{}".format(n, i, n//i)
		return "{} is prime".format(n)

		if __name__ == '__main__':
			if len(sys.argv) < 2:
				print("Usage: factors <file>")
				sys.exit(1)

				input_file = sys.argv[1]
				with open(input_file, 'r') as f:
				for line in f:
					n = int(line.strip())
					print(factorize(n))
